// File generated by FlutterFire CLI.
// This file will be auto-generated when you run `flutterfire configure`
// For now, this is a placeholder to prevent import errors

// To generate this file properly:
// 1. Complete Firebase project setup in Firebase Console
// 2. Run: flutterfire configure
// 3. This file will be automatically generated with your project's configuration

class DefaultFirebaseOptions {
  // This will be populated by FlutterFire CLI
}
